#! /usr/bin/env python
import rospy
import actionlib
from mdr_look_at_action.msg import LookAtAction, LookAtGoal

# if __name__ == '__main__':
#     rospy.init_node('look_at_client_test')
#     client = actionlib.SimpleActionClient('look_at_server', LookAtAction)
#     client.wait_for_server()
#     goal = LookAtGoal()
#     goal.goal_type = LookAtGoal.NAMED_OBJECT
#     goal.object_name = 'Trash_Bin'
#     try:
#         timeout = 45.0
#         rospy.loginfo('Sending action lib goal to look_at_server')
#         client.send_goal(goal)
#         client.wait_for_result(rospy.Duration.from_sec(int(timeout)))
#         rospy.loginfo(client.get_result())
#     except:
#         pass
